# Generated by Django 3.0.7 on 2023-06-02 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_halls', '0002_auto_20230602_1608'),
        ('movies', '0003_auto_20230602_1608'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id_screening', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('screening_time', models.DateTimeField(auto_now=True)),
                ('id_cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_halls.CinemaHall')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('id_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_screening'],
            },
        ),
    ]
