# Generated by Django 3.0.7 on 2023-06-01 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSeat',
            fields=[
                ('id_seat', models.AutoField(primary_key=True, serialize=False)),
                ('seat_type', models.CharField(choices=[(1, 'STANDARD'), (2, 'VIP')], default=1, max_length=8)),
                ('seat_code', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-seat_type'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_status', models.CharField(choices=[(1, 'FREE'), (2, 'RESERVED'), (3, 'BOOKED')], default=1, max_length=8)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.EmailNotification')),
                ('id_screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_halls.Screening')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservedSeat')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
