# Generated by Django 3.0.7 on 2023-06-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.Screening'),
        ),
        migrations.AlterField(
            model_name='reservedseat',
            name='id_seat',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
