# Generated by Django 3.0.7 on 2023-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
        ('reservations', '0002_auto_20230602_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.Screening', unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservedSeat', unique=True),
        ),
    ]
