# Generated by Django 3.0.7 on 2023-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20230602_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
