# Generated by Django 3.0.7 on 2023-06-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20230602_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id_seat', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('seat_type', models.CharField(choices=[('STANDARD', 'STANDARD'), ('VIP', 'VIP')], default='STANDARD', max_length=8)),
                ('seat_code', models.CharField(max_length=100)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-seat_type'],
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Seat'),
        ),
        migrations.DeleteModel(
            name='ReservedSeat',
        ),
    ]
