# Generated by Django 3.0.7 on 2023-06-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
        ('reservations', '0007_auto_20230602_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.Screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Seat')),
            ],
        ),
    ]
