# Generated by Django 3.0.7 on 2023-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_halls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='id_cinema_hall',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='id_movie',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='id_owner',
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='columns',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_number',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='id_hall',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='max_seats',
            field=models.IntegerField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(max_length=100),
        ),
    ]
