# Generated by Django 3.0.7 on 2023-06-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_halls', '0002_auto_20230602_1608'),
        ('reservations', '0002_auto_20230602_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
