# Generated by Django 3.0.7 on 2023-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_halls', '0003_delete_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='columns',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='hall_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='max_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(),
        ),
    ]
