# Generated by Django 3.0.7 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_halls', '0005_auto_20230602_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='cinema_hall_type',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('VIP', 'VIP')], default='2D', max_length=15, null=True),
        ),
    ]
