# Generated by Django 3.0.7 on 2023-06-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('producer', models.CharField(max_length=40)),
                ('cast', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('category', models.CharField(choices=[(1, 'HORROR'), (2, 'ACTION'), (3, 'COMEDY'), (4, 'DRAMA'), (5, 'ROMANCE')], default=3, max_length=6)),
                ('rating', models.FloatField()),
            ],
            options={
                'ordering': ['-category'],
            },
        ),
    ]
