# Generated by Django 3.0.7 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230602_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('HORROR', 'HORROR'), ('ACTION', 'ACTION'), ('COMEDY', 'COMEDY'), ('DRAMA', 'DRAMA'), ('ROMANCE', 'ROMANCE')], default='COMEDY', max_length=15, null=True),
        ),
    ]
