# Generated by Django 3.0.7 on 2023-06-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='owner',
            new_name='id_owner',
        ),
    ]
