# Generated by Django 3.0.7 on 2023-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20230602_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
